/* generated by Svelte vX.Y.Z */
import { init, safe_not_equal } from "svelte/internal";

import { BaseSvelteComponent } from "./base";

class Component extends BaseSvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Component;
